### ISSUE TITLE
Difference between xlsx.bundle.js and xlsx.js

### ISSUE THREAD

**Issue by NoelArn** [gitbrent/xlsx-js-style#1]
I am using xlsx.bundle.js and would like to make some changes for me. I know where to change the places in xlsx.js but not where they are in xlsx.bundle.js. What is the difference between these two?

**Comment by gitbrent** [comment]
You cant directly edit the bundle code. 

Fork this repo, make changes to `xlsx.js`, then run the build to produce a new bundle file.
