### ISSUE TITLE
i have set style to cell, but not reflecting

### ISSUE THREAD

**Issue by kvprasad505** [gitbrent/xlsx-js-style#4]
<script type="text/javascript" src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>

above is the CDN iam using.

```javascript
let ws = XLSX.utils.table_to_sheet(document.getElementById(id));
let wb = XLSX.utils.book_new();

 ws["B2"].s = {
      alignment: {
        wrapText: true,
      },
      font: {
        bold: true,
      },
    };
XLSX.utils.book_append_sheet(wb, ws, 'sheet1');
return XLSX.writeFile(wb, 'filename.xlsx');
```

i have set "Bold" and "wrapText" for B2 cell, but no style is reflecting, i request to suggest me a solution for this issue.

**Comment by gitbrent** [comment]
@kvprasad505 - see Issue #2
